apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: may21ibp25 
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
   app: postgres
